# Generated by Django 3.2.6 on 2021-08-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='password_reset',
            new_name='user',
        ),
    ]
